[profile.default]
src = 'contracts'
out = 'out'
libs = ['tests/foundry/lib', 'node_modules']
test = 'tests/foundry/src'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 9_999_999
via-ir = false

[fmt]
ignore = [
  './contracts/proto/**/*.sol',
  './tests/**/*.sol'
]

[profile.no_optimization]
optimizer = false

[profile.ir]
via-ir = true
