name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  contract-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Resolve dependencies
      run: npm install

    - name: Build and Check sizes
      run: make build

    - name: Run tests
      run: make test

    - name: Linting
      run: make lint

  integration-test:
    name: Integration test
    needs: contract-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Resolve dependencies
      run: npm install

    - name: Setup ganache-cli
      run: make network-development

    - name: Integration test
      run: make integration-test

    - name: Setup chains for E2E test
      run: make network-e2e

    - name: E2E test
      run: make e2e-test
